import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { getUserState, setEmail, setName } from '../store/slices/userSlice';
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import axios from 'axios';
import { URL } from '../utils/url';
import { useRouter } from 'next/router';

const Game: NextPage = ( ) => {
    const router = useRouter();
    const [error, setError] = useState("");
    const [privateData, setPrivateData] = useState("");
    const [isActive, setActive] = useState(false);
    const [highScore, setHighScore] = useState("");
    const toggleClass = () => {
        setActive(!isActive);
    };
    function logoutHandler(){
        localStorage.removeItem("authToken");
        router.push("/");
    };
    async function handleRandomScore(event: any){
        event.preventDefault();
        const config = {
            headers: {
                "Content-Type" : "application/json",
            },
            body :{
                email: localStorage.getItem("email"),
                username: localStorage.getItem("username"),
                highscore: highScore ? highScore : 0,
            }
        }

        try {
            const {data} = await axios.post(`${URL}/api/private`, 
            {
                email: localStorage.getItem("email"),
                username: localStorage.getItem("username"),
                highscore: highScore ? highScore : 0,
            },config);
        } catch (error:any) {
            setError(error?.response?.data?.error);
            setTimeout(() => {
                setError("");
            }, 5000)
        }
}
    useEffect(() => {
        if(!localStorage.getItem("authToken")){
            router.push("/login")
        }

        const fetchPrivateData = async () => {
            const config = {
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("authToken")}`
                },
                body: {
                    email: localStorage.getItem("email"),
                    username: localStorage.getItem("username"),
                    highscore: highScore ? highScore : 0,
                }
            }
            try {
                const {data} = await axios.post(`${URL}/api/private`, config);
                setPrivateData(data.data)
            }catch (error){
                localStorage.removeItem("authToken");
                setError("You are not permitted to go further. Please login")
            }
        }
        fetchPrivateData();
    }, [router]);
    return error ? (<span className="error-message">{error}</span>) :
         ( <div className={styles.container}>
            <Head>
                <title>The Morra Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
                    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet" />
            </Head>

            <section className="hero is-fullheight is-fullwidth is-default is-bold">
                <div className="hero-head">
                    <nav className="navbar is-default is-bold">
                        <div className="navbar-brand">
                            <a className="navbar-item" href="/">
                                MORRA GAME
                            </a>
                            <div className="navbar-burger burger" data-target="navbarExampleTransparentExample" onClick={toggleClass}>
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </div>

                        <div id="navbarExampleTransparentExample" className={isActive ? "navbar-menu is-active" : "navbar-menu"}>

                            <div className="navbar-end">
                                <a className="navbar-item" href="/">
                                    Home
                                </a>
                                <a className="navbar-item" href="/leaderboard">
                                    Leaderboard
                                </a>
                                <a className="navbar-item is-active" href="/game">
                                    Game
                                </a>
                                <a className="navbar-item" href="/profile">
                                    Profile
                                </a>
                                <a className="navbar-item" href="/" onClick={logoutHandler}>
                                    Logout
                                </a>
                            </div>
                        </div>
                    </nav>
                </div>
                <div className={classNames("has-text-centered", styles.animated_text)}>
                    <div>
                        <span>T</span>
                        <span>H</span>
                        <span>E</span>
                        <span>&nbsp;</span>
                        <span>M</span>
                        <span>O</span>
                        <span>R</span>
                        <span>R</span>
                        <span>A</span>
                        <span>&nbsp;</span>
                        <span>G</span>
                        <span>A</span>
                        <span>M</span>
                        <span>E</span>
                    </div>
                </div>
                <div className={classNames("hero-body", styles.container)}>
                    <div className={classNames("parallax", styles.parallax)}>
                        <div className={classNames("parallax_layer parallax_layer_0", styles.parallax_layer, styles.parallax_layer_0)}>
                            <img src="/static/1_sun.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_1", styles.parallax_layer, styles.parallax_layer_1)}>
                            <img src="/static/2_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_2", styles.parallax_layer, styles.parallax_layer_2)}>
                            <img src="/static/2_1_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_3", styles.parallax_layer, styles.parallax_layer_3)}>
                            <img src="/static/2_2_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_4", styles.parallax_layer, styles.parallax_layer_4)}>
                            <img src="/static/2_3_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_5", styles.parallax_layer, styles.parallax_layer_5)}>
                            <img src="/static/2_4_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_6", styles.parallax_layer, styles.parallax_layer_6)}>
                            <img src="/static/2_5_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_7", styles.parallax_layer, styles.parallax_layer_7)}>
                            <img src="/static/2_6_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_8", styles.parallax_layer, styles.parallax_layer_8)}>
                            <img src="/static/2_7_mountain.png" />
                        </div>
                        <div className={classNames("parallax_layer parallax_layer_9", styles.parallax_layer, styles.parallax_layer_9)}>
                            <img src="/static/2_8_mountain.png" />
                        </div>
                        <div className={classNames("parallax_cover", styles.parallax_cover)}>
                            <div className={classNames(" is-multiline columns is-centered container__juicer", styles.container__juicer)}>
                                <form onSubmit={handleRandomScore}>
                                    <div className="field">
                                        <div className="control">
                                            <input className={classNames("input is-medium is-rounded", styles.input)} type="highscore" id="highscore" value={highScore} placeholder="Highscore" required 
                                            onChange={(e) => setHighScore(e.target.value)}/>
                                        </div>
                                    </div>
                                    <button className="button is-block is-primary is-medium is-rounded" type="submit">Add current user to leaderboard</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default Game;
